export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const USER_LOADED="USER_LOADED";
export const USER_LOGGED_IN="USER_LOGGED_IN";
export const USER_LOGGED_OUT="USER_LOGGED_OUT";